### ISSUE TITLE
Code not running

### ISSUE THREAD

**Issue by ImreMD** [valentin994/todo-fastapi-react-mongo#1]
Delete call not working get the following message:

DELETE http://localhost:8000/api/todo/$%7Btitle%7D 404 (Not Found)

title variable is inserted in URL everything is forced to string

**Comment by ImreMD** [comment]
It's okay - some weird typo. You can delete the issue

**Comment by ImreMD** [comment]
I will reopen finally it was both a typo (which blocks requests from the swagger docs) but there's also a bug (in my opinion) in the deleteHandle url it should be: axios.delete('http://localhost:8000/api/todo/'+ title) NOT axios.delete(`http://localhost:8001/api/todo/${title}`) the later causes the issue of stringifying the address.

**Comment by valentin994** [comment]
I forgot about this repo tbh, thank you for getting into it, I suppose this one is on medium? Do you want to open a pr or should I fix it up?

**Comment by ImreMD** [comment]
:-) yes, I read it on medium having some trouble with react and delete calls. As you like may be it&#39;s a good idea as this same kind of error appears also in some youtube tuto so if somebody will read your post they will find some help. br  
            
          
     
      
       
        Dnia 25 kwietnia 2022 08:27 Valentin Vareskic ***@***.***&gt; napisał(a):
       
    
       
         
 I forgot about this repo tbh, thank you for getting into it, I suppose this one is on medium? Do you want to open a pr or should I fix it up?

**Comment by valentin994** [comment]
Updated it
